server:
  port: 8081

spring:
  application:
    name: employee-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: changeit
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"