server:
  port: 8081

spring:
  application:
    name: employee-service
  datasource:
    driver-class-name: org.h2.Driver
    url: dbc:h2:mem:employee
    username: root
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"